# Generated by Django 5.2.8 on 2026-01-29 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobbydetail',
            name='icon',
        ),
    ]
